# Experiment Specific
experiment_name: 'UNet_Abdomen_MR2CT_Adapt_PFA'
data_root: '/workspace/MICCAI23-ProtoContra-SFDA/datasets/chaos'
save_root: '/workspace/MICCAI23-ProtoContra-SFDA/results/Target_Adapt/'
source_model_path: '/workspace/MICCAI23-ProtoContra-SFDA/results/Source_Seg/UNet_Abdomen_MR_Seg/exp_0_time_2026-03-27 07:05:34/saved_models/best_model_epoch_79_dice_0.9434.pth'
target_sites:
- 'CT'
resume_dir: ''
continue_train: False
total_epochs: 5

random_seed: 999
organ_list:
- 'Spleen'
- 'R.Kidney'
- 'L.Kidney'
- 'Liver'

# Dataloader Setting
patient_level_dataloader: False
img_size:
- 256
- 256
batch_size: 16
num_workers: 8

# Model 
arch: 'UNet'
use_prototype: False
update_prototype: False
input_dim: 3
feat_dim: 32
output_dim: 64
num_classes: 5
num_prototypes: 1

# Optim parameters
lr: 0.0001

# Loss parameters
nav_t: 0.1
beta: 0.001
s_par: 0.5

# display
save_steps: 50
eval_steps: 5
display_steps: 40
save_visuals: True

# test
test: False
