# Experiment Specific
experiment_name: 'UNet_Abdomen_CT2MR_Adapt_CL'
data_root: '/opt/data/private/MICCAI23-ProtoContra-SFDA/datasets/chaos'
save_root: '/opt/data/private/MICCAI23-ProtoContra-SFDA/results/Target_Adapt/'
source_model_path: '/opt/data/private/MICCAI23-ProtoContra-SFDA/results/Target_Adapt/UNet_Abdomen_CT2MR_Adapt_PFA/exp_2_time_2026-03-26 11:38:17/saved_models/best_model_step_15_dice_0.8960.pth'
target_sites:
- 'MR'
resume_dir: ''
continue_train: False
total_epochs: 5
random_seed: 999
organ_list:
- 'Spleen'
- 'R.Kidney'
- 'L.Kidney'
- 'Liver'

# Dataloader Setting
patient_level_dataloader: False
img_size:
- 256
- 256
batch_size: 16
num_workers: 8

# Model 
arch: 'UNet'
use_prototype: False
update_prototype: False
input_dim: 3
feat_dim: 32
output_dim: 64
num_classes: 5
num_prototypes: 1

# Optim parameters
lr: 0.0001

# Loss parameters
nav_t: 0.1
beta: 0.001
s_par: 0.5

# Pseudo Loss parameters
use_pseudo: False
drop_percent: 80

# Constrastive learning parameters
use_contra: True
use_source_prototypes: False
momentum_prototype: False
num_queries: 64
num_negatives: 256
current_class_threshold: 0.3
low_entropy_threshold: 20
low_rank: 2
high_rank: 5

# display
save_steps: 10
eval_steps: 5
display_steps: 40
save_visuals: True

# test
test: False